config/routes.rb
Rails.application.routes.draw do
  # get 'hello_world', to: 'hello_world#index'
  # get 'weather/find_city'
  devise_for :users
  root to: 'pages#home'

  resources :users, only: [:index, :new, :create ] do
    member do
      post :follow
      post :unfollow
    end
  end
  resources :experiences, only: [:index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/experience.rb
class Experience < ApplicationRecord
  has_many :posts
  belongs_to :user
  validates :content, presence: true
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location
  mount_uploader :photo, PhotoUploader
end

app/models/follow.rb
class Follow < ApplicationRecord
 belongs_to :follower, foreign_key: 'follower_id', class_name: 'User'
  belongs_to :following, foreign_key: 'following_id', class_name: 'User'
end

app/models/posts.rb
class Posts < ApplicationRecord
  belongs_to :experiences
  belongs_to :user
  validates :content, presence: true, length: { maximum: 200 }
  mount_uploader :photo, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :experiences
  has_many :posts
  has_many :follower_relationships, foreign_key: :following_id, class_name: 'Follow'
  has_many :followers, through: :follower_relationships, source: :follower

  has_many :following_relationships, foreign_key: :follower_id, class_name: 'Follow'
  has_many :following, through: :following_relationships, source: :following
  def follow(user_id)
    following_relationships.create(following_id: user_id)
  end

  def unfollow(user_id)
    following_relationships.find_by(following_id: user_id).destroy
  end

  def is_following?(user_id)
    relationship = Follow.find_by(follower_id: id, following_id: user_id)
    return true if relationship
  end
end

app/models/weather.rb
class Weather < ApplicationRecord



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
   respond_to :js, :json, :html

  def index
    @experiences = Experience.geocoded
    @markers = @experiences.map do |experience|
      {
        lat: experience.latitude,
        lng: experience.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { flat: flat })
      }
    end
   end


def new
    @experience = Experience.new
  end

def create
  @experience = Experience.new(experience_params)
    @experience.user = current_user
  if @experience.save
    # CALL THE create_pictures METHOD AFTER @product.save
    create_pictures
    redirect_to experience_path(@experience)
  else
    render :new
  end
end

private

def experience_params
    params.require(:experience).permit(:content, :gear, :location, :photo)
  end



def create_pictures
  photos = params.dig(:experience, :pictures) || []
  photos.each do |photo|
    @experience.pictures.create(photo: photo)
  end
end
end

app/controllers/hello_world_controller.rb
# frozen_string_literal: true

class HelloWorldController < ApplicationController
  layout "hello_world"

  def index
    @hello_world_props = { name: "Stranger" }
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:follow, :unfollow]

  def index
    @users = User.where.not(id: current_user.id)
  end

  def follow
    if current_user.follow(@user.id)
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    end
  end

  def unfollow
    if current_user.unfollow(@user.id)
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js { render action: :follow }
      end
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController
  def find_city
    @results = getOpenWeatherCities(params[:q])
    respond_to do |format|
    format.js { render json: @results }
    end
  end

  def get_open_weather_cities(query)
        require 'net/http'
        require 'json'
        require 'erb'
        query_escaped=ERB::Util.url_encode(query)
        appid = ConcertoConfig["open_weather_map_api_key"]
        url = "http://api.openweathermap.org/data/2.5/find?q=#{query_escaped}&type=like&mode=json&appid=#{appid}"
        return Net::HTTP.get(URI(url))
     end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/experiences/_default.html.erb
<dl>
  <h1>Weather</h1>
  <dt>City</dt>
  <dd><%= content.config['location_name'] %></dd>
  <dt>Units</dt>
  <dd><%= Weather::UNITS[content.config['units']] %></dd>
  <dt>Icon Style</dt>
  <dd><%= Weather::FONTS[content.config['font_name']] %></dd>
  <dt>Forecast type</dt>
  <dd><%= Weather::FORECAST[content.config['forecast_type']] %></dd>
  <dt>Last Successful Update</dt>
  <dd><%= content.config.include?('last_ok_refresh') ? Time.at(content.config['last_ok_refresh']).strftime('%c') : 'Never' %></dd>
  <dt>Last Attempted Update</dt>
  <dd><%= content.config.include?('last_refresh_attempt') ? distance_of_time_in_words_to_now(Time.at(content.config['last_refresh_attempt'])).titleize + ' Ago' : 'Never' %></dd>
  <dt>Min. Refresh Interval</dt>
  <dd><%= distance_of_time_in_words(content.config['interval'].to_i) %></dd>
  <dt>Format String</dt>
  <div class="input">
  <textarea rows='6' readonly>
  <%= content.config['format_string'] %>
  </textarea>
  </div>
</dl>

app/views/experiences/_find_city.html.erb
<h1>Weather#find_city</h1>
<p>Find me in app/views/weather/find_city.html.erb</p>
<h1>Weather for <%= content.config['location_name'] %></h1>

app/views/experiences/_info_window.html.erb
_info_window.html.erb
<h2><%= experience.content %></h2>
<p><%= experience.photo %></p>

app/views/experiences/_top.html.erb
<%= javascript_include_tag "concerto_weather/application" %>
<%= stylesheet_link_tag "concerto_weather/application" %>

<fieldset>
  <legend><span>Weather</span></legend>
  <div class="row-fluid">
    <% if ConcertoConfig["open_weather_map_api_key"].blank? %>
    <div class='alert alert-warning'>
      The OpenWeatherMap API Key under Settings appears to be blank.  An API key is required for this content.
    </div>
    <% end %>
    <div class='span4'>
    <%= form.fields_for :config do |config| %>
      <div class="clearfix">
        <%= config.label :city_query, "City Search" %>
        <div class="input">
          <%= config.text_field :city_query, placeholder:"Name or Zipcode", value: @content.config['city_id'] %>
          <%= button_tag type: "button", :class => "btn", onclick: "searchForCityInfo()" do %>
            <i class="fa fa-refresh"></i>
          <% end %>
        </div>
      </div>
      <div class="clearfix">
        <%= config.label :units %>
        <div class="input">
          <%= config.select :units, Weather::UNITS.map {|k,v| [v, k]}, :selected => @content.config['units'] %>
        </div>
      </div>
      <div class="clearfix">
        <%= config.label :font_name %>
        <div class="input">
          <%= config.select :font_name, Weather::FONTS.map {|k,v| [v, k]}, :selected => @content.config['font_name'] %>
        </div>
      </div>
      <div class="clearfix">
        <%= config.label :forecast_type %>
        <div class="input">
          <%= config.select :forecast_type, Weather::FORECAST.map {|k,v| [v, k]}, :selected => @content.config['forecast_type'] %>
        </div>
      </div>
      <div class="clearfix">
        <%= config.label :format_string, "Format String" %>
        <div class="input">
          <%= config.text_area :format_string, placeholder:"Format String for the weather output", value: @content.config['format_string'], rows: 6 %>
        </div>
      </div>

      <%= config.hidden_field :lat %>
      <%= config.hidden_field :lng %>
    <% end %>
    </div>
    <div class="clearfix">
      <div class='city-info span8'></div>
    </div>
  </div>
</fieldset>

app/views/experiences/index.html.erb
<div class = "mapbody"
  id="map"
  style="width: 100%;
  height: 45vh;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  >
  </div>

<div id="geocoder" class="geocoder"></div>


 <br />
<%= form_tag experiences_path, method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control search-form",
          placeholder: "find an experience"
        %>
        <%= submit_tag "Search", class: "my-4 btn-solid btn-clean-border" %>
      <% end %>

 <% @experiences.each do |experience| %>
  <%= link_to "", new_experience_path(@experience), class: "card-clickable" %>
  <img src="<%= cl_image_path experience.photo, crop: :fill %>" alt="">
  <h2><%= link_to experience.content, experience %></h2>
              <p id="text"><%= experience.gear %></p>
               <%= cl_image_tag experience.user.photo, class: "card-trip-user avatar-bordered" %>
               <% end %>

<%= link_to "follow others and see what they are upto", users_path, class: "nav-link" %>
<div class="container">
      <div class="row">
        <div class="col-sm-8 offset-sm-2">
          <!-- <form class="d-flex align-items-center">
            <input type="text" id="input" placeholder="Enter beach name">
            <select id="input" class="select2"></select>

          </form> -->
           <!-- <input type="submit" value="Get the weather" class="btn btn-primary ml-3">
           <a href="" class="btn btn-success w-100" id="current-location">Get weather </a> -->
          <div class="card mt-4 mb-5">
            <div class="card-body">
              <h1>Weather in <span id="city"></span></h1>
              <!-- <h3 id="date" class="gray-text"></h3> -->
              <div id="weather">
                <!-- <p id="description"></p> -->
                <div class="d-flex">
                  <img src="" alt="Weather Icon" id="icon">

                  <h2 id="temperature"></h2>


                </div>
                <div>
                  <h5>Feels like:</h5>
                  <p id ="feels"></p>

                </div>
                <div>
                  <h3> Wind Conditions</h3>
                  <h5>Average Wind speed:</h5>
                  <p id = "speed"></p>
                  <h5>Wind Direction:</h5>
                  <p id ="direction"></p>
                    <p id ="update"></p>



<h1>Hello World</h1>
 <%#= react_component("ReactWeather", props: @ReactWeather_props, prerender: false) %>
<div id ='root' ></div>
                </div>




                <div>


                  </div>

                </div>
              </div>




            </div>
          </div>

        </div>
        <div class="container ">







      </div>
    </div>

app/views/experiences/new.html.erb
<div class="form-container create-form-container">
  <div class="create-form-banner">
    <p>Who do you want to save the world?</p>
    <%= simple_form_for(@experience) do |f| %>
      <%= f.input :content, placeholder: "Name", label: false %>
      <%= f.input :gear, placeholder: "Price", label: false %>
      <%= f.input :location, placeholder: "Location", label: false %>
      <%= f.input :photo, label: false, class: "btn-photo-upload" %>
      <%= f.input :pictures, as: :file, input_html: { multiple: true } %>
      <%= f.input :photo_cache, as: :hidden %>
      <%= f.submit "Add to a moment", class: "btn-solid btn-block" %>
    <% end %>
  </div>
</div>

app/views/hello_world/index.html.erb
<h1>Hello World</h1>
<%= react_component("ReactWeather", props: @reactweather_props, prerender: true) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
   
  </body>
</html>

app/views/layouts/hello_world.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactOnRailsWithWebpacker</title>
    <%= csrf_meta_tags %>
    <%= javascript_pack_tag 'react-weather' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/maps/map.html.erb
map.html.erb

app/views/pages/home.html.erb
<div class ="banner">
<div class="banner-home" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1574512826577-47e69cc9d347?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60);">
<div class = home-container>
    <div class="container">
      <%= image_tag("SoulChase.png", :alt => "rss feed") %>
    </div>
    <%= link_to "Explore an experience",  experiences_path, class: "btn btn-ghost" %>
  </div>
</div>
<div class="banner-home">
  <%= image_tag("SoulChase.png", :alt => "rss feed") %>
  <div class = "second-banner">
    <div>
      <h3>Chase it, Follow the Wind ,Discover the dream ,Live your Passion</h3>
      <p>Find New challenging places see where others have discover,Share with other windholics your discoveries</p>
    </div>
    <img src= "https://images.unsplash.com/photo-1505928094501-610ccb53980d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60">
  </div>
</div>
</div>
<div class="banner-home">
  <div class ="third-banner">
    <img src="https://images.unsplash.com/photo-1565010505272-f1fbbb6abdfc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" >
    <div class="card-product-infos">
      <h2></h2>
      <p> </p>
    </div>
  </div>
</div>

<div class="footer">
      <div class="footer-links">
        <a href="#"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
      </div>
      <div class="footer-copyright">
       Soulwind trademark
      </div>
    </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag ("SoulChase.png")%>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Experiences", experiences_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%#= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
      </ul>
    </div>
  </div>

app/views/users/_user.html.erb
<li data-user=<%= user.id %>>
  <%= user.email %>
  <% if current_user.is_following?(user.id) %>
    <%= link_to "Unfollow", unfollow_user_path(user.id), method: :post, remote: true %>
  <% else %>
    <%= link_to "Follow", follow_user_path(user.id), method: :post, remote: true %>
  <% end %>
</li>

app/views/users/follow.js.erb
function renderUser(userHTML) {
  const user = document.querySelector("[data-user='<%= @user.id %>']");
  user.outerHTML = userHTML;
}

renderUser('<%= j render @user %>');

app/views/users/index.html.erb
<h1>Users:</h1>
<ul>
  <%= render @users %>
</ul>

app/views/weather/_form_top.html.erb
<%= javascript_include_tag "concerto_weather/application" %>
<%= stylesheet_link_tag "concerto_weather/application" %>

<fieldset>
  <legend><span>Weather</span></legend>
  <div class="row-fluid">
    <% if ConcertoConfig["open_weather_map_api_key"].blank? %>
    <div class='alert alert-warning'>
      The OpenWeatherMap API Key under Settings appears to be blank.  An API key is required for this content.
    </div>
    <% end %>
    <div class='span4'>
    <%= form.fields_for :config do |config| %>
      <div class="clearfix">
        <%= config.label :city_query, "City Search" %>
        <div class="input">
          <%= config.text_field :city_query, placeholder:"Name or Zipcode", value: @content.config['city_id'] %>
          <%= button_tag type: "button", :class => "btn", onclick: "searchForCityInfo()" do %>
            <i class="fa fa-refresh"></i>
          <% end %>
        </div>
      </div>
      <div class="clearfix">
        <%= config.label :units %>
        <div class="input">
          <%= config.select :units, Weather::UNITS.map {|k,v| [v, k]}, :selected => @content.config['units'] %>
        </div>
      </div>
      <div class="clearfix">
        <%= config.label :font_name %>
        <div class="input">
          <%= config.select :font_name, Weather::FONTS.map {|k,v| [v, k]}, :selected => @content.config['font_name'] %>
        </div>
      </div>
      <div class="clearfix">
        <%= config.label :forecast_type %>
        <div class="input">
          <%= config.select :forecast_type, Weather::FORECAST.map {|k,v| [v, k]}, :selected => @content.config['forecast_type'] %>
        </div>
      </div>
      <div class="clearfix">
        <%= config.label :format_string, "Format String" %>
        <div class="input">
          <%= config.text_area :format_string, placeholder:"Format String for the weather output", value: @content.config['format_string'], rows: 6 %>
        </div>
      </div>

      <%= config.hidden_field :lat %>
      <%= config.hidden_field :lng %>
    <% end %>
    </div>
    <div class="clearfix">
      <div class='city-info span8'></div>
    </div>
  </div>
</fieldset>